-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE = 27022002000

LOCATION_LISTING = {
	 { "@Overworld/Forest of Time/Impa Gift/Forest of Time: Impa's Gift"},
	 { "@Overworld/Forest of Time/Nayru's House/Forest of Time: Nayru's House"},
	 { "@Overworld/Forest of Time/Tingle/Forest of Time: Tingle Present"},
	 { "@Overworld/Forest of Time/Tingle/Forest of Time: Tingle Upgrade"},
	 { "@Overworld/Lynna City/Chest Past Burnt Tree/Lynna City: Chest Past Burnt Tree"},
	 { "@Overworld/Lynna City/Shop/Lynna City: Shop Item #1"},
	 { "@Overworld/Lynna City/Shop/Lynna City: Shop Item #2"},
	 { "@Overworld/Lynna City/Shop/Lynna City: Shop Item #3"},
	 { "@Overworld/Lynna City/Hidden Shop/Lynna City: Hidden Shop Item #1"},
	 { "@Overworld/Lynna City/Hidden Shop/Lynna City: Hidden Shop Item #2"},
	 { "@Overworld/Lynna City/Hidden Shop/Lynna City: Hidden Shop Item #3"},
	 { "@Overworld/Lynna City/Mayor Plen's House/Lynna City: Mayor Plen's House"},
	 { "@Overworld/Lynna City/Vasu's Gift/Lynna City: Vasu's Gift"},
	 { "@Overworld/Lynna City/Maku Tree Gift/Lynna City: Maku Tree gift"},
	 { "@Overworld/Lynna City/Mamamu Yan Trade/Lynna City: Mamamu Yan Trade"},
	 { "@Overworld/Lynna City/Comedian Trade/Lynna City: Comedian Trade"},
	 { "@Overworld_Past/Lynna Village/Gasha Farmer/Lynna Village: Gasha Farmer"},
	 { "@Overworld_Past/Lynna Village/Advance Shop/Lynna Village: Advance Shop Item #1"},
	 { "@Overworld_Past/Lynna Village/Advance Shop/Lynna Village: Advance Shop Item #2"},
	 { "@Overworld_Past/Lynna Village/Advance Shop/Lynna Village: Advance Shop Item #3"},
	 { "@Overworld_Past/Lynna Village/Baseball/Lynna Village: Baseball"},
	 { "@Overworld_Past/Lynna Village/Postman Trade/Lynna Village: Postman Trade"},
	 { "@Overworld_Past/Lynna Village/Toilet Hand Trade/Lynna Village: Toilet Hand Trade"},
	 { "@Overworld_Past/Lynna Village/Sad Boi Trade/Lynna Village: Depressed Child Trade"},
	 { "@Overworld_Past/Lynna Village/Supervisor/Black Tower (Past): Supervisor"},
	 { "@Overworld_Past/Lynna Village/Black Tower Heart Piece/Black Tower (Past): Heart Piece"},
	 { "@Overworld_Past/Lynna Village/Ambi's Palace/Ambi's Palace: East Wing Chest"},
	 { "Nayru"},
	 { "@Overworld_Past/Lynna Village/Cave Near Restoration Wall/West Lynna: Cave Near Restoration Wall"},
	 { "@Overworld/Lynna City/Dirt Pile/South Shore (Present): Dirt Pile"},
	 { "@Overworld_Past/Lynna Village/Rafton Trade/South Shore (Past): Rafton Trade"},
	 { "@Overworld/Yoll Graveyard/Cheval's Test/Yoll Graveyard: Cheval's Test"},
	 { "@Overworld/Yoll Graveyard/Cheval's Invention/Yoll Graveyard: Cheval's Invention"},
	 { "@Overworld/Yoll Graveyard/Grave Under The Tree/Yoll Graveyard: Grave Under The Tree"},
	 { "@Overworld/Yoll Graveyard/Syrup's Shop/Yoll Graveyard: Syrup Shop Item #1"},
	 { "@Overworld/Yoll Graveyard/Syrup's Shop/Yoll Graveyard: Syrup Shop Item #2"},
	 { "@Overworld/Yoll Graveyard/Syrup's Shop/Yoll Graveyard: Syrup Shop Item #3"},
	 { "@Overworld/Yoll Graveyard/Poe's Gift/Yoll Graveyard: Poe's Gift"},
	 { "@Overworld/Yoll Graveyard/Heart Piece/Yoll Graveyard: Heart Piece"},
	 { "@Overworld/Fairies' Woods/Single Chest/Fairies' Woods: Single Chest"},
	 { "@Overworld_Past/Deku Forest/Chest in Central Cave/Deku Forest: Chest in Central Cave"},
	 { "@Overworld_Past/Deku Forest/Chest in Path to Seed Tree/Deku Forest: Chest in Path to Seed Tree"},
	 { "@Overworld_Past/Deku Forest/Soldier's Reward/Deku Forest: Soldier's Reward"},
	 { "@Overworld_Past/Deku Forest/Terrace in Cave Under Tree/Deku Forest: Terrace in Cave Under Tree"},
	 { "@Overworld/Crescent Island/Underwater Maze Cave/Crescent Island (Present): Underwater Maze Cave"},
	 { "@Overworld/Crescent Island/Tokay Chef Trade/Crescent Island (Present): Tokay Chef Trade"},
	 { "@Overworld_Past/Crescent Island/Water Cave Tokay/Crescent Island (Past): Water Cave Tokay"},
	 { "@Overworld_Past/Crescent Island/Crystal Cave Chest/Crescent Island (Past): Crystal Cave Chest"},
	 { "@Overworld_Past/Crescent Island/Bomb Cave Chest/Crescent Island (Past): Bomb Cave Chest"},
	 { "@Overworld_Past/Crescent Island/Tokay Chicken Hut/Crescent Island (Past): Tokay Chicken Hut"},
	 { "@Overworld_Past/Crescent Island/Wild Tokay Prize/Crescent Island (Past): Wild Tokay Prize"},
	 { "@Overworld_Past/Crescent Island/Tokay Market/Crescent Island (Past): Market Item #1"},
	 { "@Overworld_Past/Crescent Island/Tokay Market/Crescent Island (Past): Market Item #2"},
	 { "@Overworld_Past/Crescent Island/Pot Cave/Crescent Island (Past): Pot Cave"},
	 { "@Overworld/Nuun Highlands/Southern Cave/Nuun Highlands: Southern Cave"},
	 { "@Overworld/Nuun Highlands/Happy Mask Salesman Trade/Nuun Highlands: Happy Mask Salesman Trade"},
	 { "@Overworld_Past/Symmetry Village/Symmetry Village Main House/Symmetry Village: Brothers"},
	 { "@Overworld_Past/Symmetry Village/Symmetry Village Main House/Symmetry Village: Skinny Guy Trade"},
	 { "@Overworld/Talus Peaks/Bomb Fairy/Talus Peaks (Present): Bomb Fairy"},
	 { "@Overworld/Talus Peaks/Southeastern Chest/Talus Peaks (Present): Southeastern Chest"},
	 { "@Overworld/Talus Peaks/Heart Piece/Talus Peaks (Present): Heart Piece"},
	 { "@Overworld_Past/Talus Peaks/Tokkey's Composition/Talus Peaks (Past): Tokkey's Composition"},
	 { "@Overworld_Past/Talus Peaks/Patch/Talus Peaks (Past): Tuni Nut Restoration"},
	 { "@Overworld_Past/Talus Peaks/Patch/Talus Peaks (Past): Broken Sword Restoration"},
	 { "@Overworld/Rolling Ridge/Rolling Ridge Entrance/Rolling Ridge Base (Present): Terrace Chest"},
	 { "@Overworld/Rolling Ridge/Goron caves (Present)/Rolling Ridge Base (Present): First Goron Dance"},
	 { "@Overworld/Rolling Ridge/Pool in Mermaid Cave Entrance/Rolling Ridge Base (Present): Pool in Mermaid Cave Entrance"},
	 { "@Overworld/Rolling Ridge/Goron caves (Present)/Rolling Ridge Base (Present): Trade With Doorkeeper Goron"},
	 { "@Overworld_Past/Rolling Ridge/Rolling Ridge Entrance/Rolling Ridge Base (Past): Goron Elder"},
	 { "@Overworld_Past/Rolling Ridge/Goron caves/Rolling Ridge Base (Past): Goron Dance With Letter"},
	 { "@Overworld_Past/Rolling Ridge/Goron caves/Rolling Ridge Base (Past): Trade With Doorkeeper Goron"},
	 { "@Overworld_Past/Rolling Ridge/East Ridge Base/Rolling Ridge Base (Past): Chest Behind Cracked Rocks"},
	 { "@Overworld_Past/Rolling Ridge/East Ridge Base/Rolling Ridge Base (Past): Chest Beyond Diamonds"},
	 { "@Overworld/Rolling Ridge/Rolling Ridge Entrance/Rolling Ridge (Present): West Stairs Cave Chest"},
	 { "@Overworld/Rolling Ridge/Moblin Keep/Rolling Ridge (Present): Cave Under Moblin Keep"},
	 { "@Overworld/Rolling Ridge/Moblin Keep/Rolling Ridge (Present): Defeat Great Moblin"},
	 { "@Overworld/Rolling Ridge/Rolling Ridge Entrance/Rolling Ridge (Present): Goron's Hiding Place"},
	 { "@Overworld_Past/Rolling Ridge/Goron caves/Rolling Ridge (Present): Bush Cave Chest"},
	 { "@Overworld/Rolling Ridge/Target Carts Minigame/Rolling Ridge (Present): Target Carts 1st Prize"},
	 { "@Overworld/Rolling Ridge/Target Carts Minigame/Rolling Ridge (Present): Target Carts 2nd Prize"},
	 { "@Overworld/Rolling Ridge/Goron caves (Present)/Rolling Ridge (Present): Big Bang Prize"},
	 { "@Overworld/Rolling Ridge/Goron caves (Present)/Rolling Ridge (Present): Northeast Cave Chest"},
	 { "@Overworld/Rolling Ridge/Goron caves (Present)/Rolling Ridge (Present): Chest in Diamonds Room"},
	 { "@Overworld/Rolling Ridge/Rolling Ridge Entrance/Rolling Ridge (Present): Heart Piece in Westmost Cave"},
	 { "@Overworld/Rolling Ridge/Far Northeast Heart Piece/Rolling Ridge (Present): Far Northeast Heart Piece"},
	 { "@Overworld_Past/Rolling Ridge/Cave in Goron Face/Rolling Ridge (Past): Cave in Goron Face"},
	 { "@Overworld_Past/Rolling Ridge/Treasure Hunting Goron/Rolling Ridge (Past): Treasure Hunting Goron"},
	 { "@Overworld_Past/Rolling Ridge/Baseball/Rolling Ridge (Past): Baseball"},
	 { "@Overworld_Past/Rolling Ridge/Goron caves/Rolling Ridge (Past): Trade With Graceful Goron's Friend"},
	 { "@Overworld/Zora Seas/Western Pool Chest/Zora Village (Present): Western Pool Chest"},
	 { "@Overworld/Zora Seas/Zora Palace (Present)/Zora Village (Present): Zora Palace Chest"},
	 { "@Overworld/Zora Seas/Statues Cave/Zora Village (Present): Statues Cave"},
	 { "@Overworld/Zora Seas/Fairies' Coast Chest/Zora Village (Present): Fairies' Coast Chest"},
	 { "@Overworld/Zora Seas/Zora Palace (Present)/Zora Village (Present): Zora King Gift"},
	 { "@Overworld/Zora Seas/Zora's Reward/Zora Village (Present): Zora's Reward"},
	 { "@Overworld/Zora Seas/Old Man/Eyeglass Island Library (Present): Old Man"},
	 { "@Overworld_Past/Zora Seas/Old Man/Eyeglass Island Library (Past): Old Man"},
	 { "@Overworld/Zora Seas/Southeast Island Chest/Zora Seas (Present): Southeast Island Chest"},
	 { "@Overworld_Past/Zora Seas/Fisherman's Island Cave/Zora Seas (Past): Fisherman's Island Cave"},
	 { "@Overworld_Past/Sea of Storms/Piratian Captain/Sea of Storms (Past): Piratian Captain"},
	 { "@Overworld_Past/Sea of Storms/Underwater Cave/Sea of Storms (Past): Underwater Cave"},
	 { "@Overworld_Past/Sea of no Return/Chest Under Statue/Sea of No Return: Chest Under Statue"},
	 { "@Overworld_Past/Sea of no Return/Old Zora Trade/Coast of No Return: Old Zora Trade"},
	 { "@Overworld/Maple Trade/Maple Trade"},
	 { "@Dungeons/Maku Path (D0)/Heart Piece/Maku Path: Heart Piece"},
	 { "@Dungeons/Maku Path (D0)/Key Chest/Maku Path: Key Chest"},
	 { "@Dungeons/Maku Path (D0)/Basement/Maku Path: Basement"},
	 { "@Dungeons/Spirit's Grave (D1)/One-Button Chest/Spirit's Grave: One-Button Chest"},
	 { "@Dungeons/Spirit's Grave (D1)/Two-Buttons Chest/Spirit's Grave: Two-Buttons Chest"},
	 { "@Dungeons/Spirit's Grave (D1)/Wide Room/Spirit's Grave: Wide Room"},
	 { "@Dungeons/Spirit's Grave (D1)/Crystal Room/Spirit's Grave: Crystal Room"},
	 { "@Dungeons/Spirit's Grave (D1)/Crossroad/Spirit's Grave: Crossroad"},
	 { "@Dungeons/Spirit's Grave (D1)/West Terrace/Spirit's Grave: West Terrace"},
	 { "@Dungeons/Spirit's Grave (D1)/Pot Chest/Spirit's Grave: Pot Chest"},
	 { "@Dungeons/Spirit's Grave (D1)/East Terrace/Spirit's Grave: East Terrace"},
	 { "@Dungeons/Spirit's Grave (D1)/Ghini Drop/Spirit's Grave: Ghini Drop"},
	 { "@Dungeons/Spirit's Grave (D1)/Basement/Spirit's Grave: Basement"},
	 { "@Dungeons/Spirit's Grave (D1)/Pumpkin Head/Spirit's Grave: Boss"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Color Room/Wing Dungeon (1F): Color Room"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Bombed Terrace/Wing Dungeon (1F): Bombed Terrace"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Moblin Platform/Wing Dungeon (1F): Moblin Platform"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Rope Room/Wing Dungeon (1F): Rope Room"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Ladder Chest/Wing Dungeon (1F): Ladder Chest"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Moblin Drop/Wing Dungeon (1F): Moblin Drop"},
	 { "@Dungeons/Wing Dungeon (D2)/(1F): Statue Puzzle/Wing Dungeon (1F): Statue Puzzle"},
	 { "@Dungeons/Wing Dungeon (D2)/(B1F): Thwomp Shelf/Wing Dungeon (B1F): Thwomp Shelf"},
	 { "@Dungeons/Wing Dungeon (D2)/(B1F): Thwomp Tunnel/Wing Dungeon (B1F): Thwomp Tunnel"},
	 { "@Dungeons/Wing Dungeon (D2)/(B1F): Basement Chest/Wing Dungeon (B1F): Basement Chest"},
	 { "@Dungeons/Wing Dungeon (D2)/(B1F): Basement Drop/Wing Dungeon (B1F): Basement Drop"},
	 { "@Dungeons/Wing Dungeon (D2)/Head Thwomp/Wing Dungeon (1F): Boss"},
	 { "@Dungeons/Moonlit Grotto (D3)/(B1F): Bridge Chest/Moonlit Grotto (1F): Bridge Chest"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Mimic Room/Moonlit Grotto (1F): Mimic Room"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Bush Beetle Room/Moonlit Grotto (1F): Bush Beetle Room"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Crossroad/Moonlit Grotto (1F): Crossroad"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Pols Voice Chest/Moonlit Grotto (1F): Pols Voice Chest"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Armos Drop/Moonlit Grotto (1F): Armos Drop"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Statue Drop/Moonlit Grotto (1F): Statue Drop"},
	 { "@Dungeons/Moonlit Grotto (D3)/(1F): Six Blocs Drop/Moonlit Grotto (1F): Six Blocs Drop"},
	 { "@Dungeons/Moonlit Grotto (D3)/(B1F): Moldorm Drop/Moonlit Grotto (B1F): Moldorm Drop"},
	 { "@Dungeons/Moonlit Grotto (D3)/(B1F): East/Moonlit Grotto (B1F): East"},
	 { "@Dungeons/Moonlit Grotto (D3)/(B1F): Torch Chest/Moonlit Grotto (B1F): Torch Chest"},
	 { "@Dungeons/Moonlit Grotto (D3)/(B1F): Conveyor Belt Room/Moonlit Grotto (B1F): Conveyor Belt Room"},
	 { "@Dungeons/Moonlit Grotto (D3)/Shadow Hag/Moonlit Grotto (B1F): Boss"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Second Crystal Switch/Skull Dungeon (1F): Second Crystal Switch"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Lava Pot Chest/Skull Dungeon (1F): Lava Pot Chest"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Small Floor Puzzle/Skull Dungeon (1F): Small Floor Puzzle"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): First Chest/Skull Dungeon (1F): First Chest"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Minecart Chest/Skull Dungeon (1F): Minecart Chest"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Cube Chest/Skull Dungeon (1F): Cube Chest"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): First Crystal Switch/Skull Dungeon (1F): First Crystal Switch"},
	 { "@Dungeons/Skull Dungeon (D4)/(1F): Color Tile Drop/Skull Dungeon (1F): Color Tile Drop"},
	 { "@Dungeons/Skull Dungeon (D4)/(B1F): Large Floor Puzzle/Skull Dungeon (B1F): Large Floor Puzzle"},
	 { "@Dungeons/Skull Dungeon (D4)/Eyesoar/Skull Dungeon (B1F): Boss"},
	 { "@Dungeons/Crown Dungeon (D5)/(1F): Diamond Chest/Crown Dungeon (1F): Diamond Chest"},
	 { "@Dungeons/Crown Dungeon (D5)/(1F): Eyes Chest/Crown Dungeon (1F): Eyes Chest"},
	 { "@Dungeons/Crown Dungeon (D5)/(1F): Three-Statue Puzzle/Crown Dungeon (1F): Three-Statue Puzzle"},
	 { "@Dungeons/Crown Dungeon (D5)/(1F): Blue Peg Chest/Crown Dungeon (1F): Blue Peg Chest"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Like-Like Chest/Crown Dungeon (B1F): Like-Like Chest"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Red Peg Chest/Crown Dungeon (B1F): Red Peg Chest"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Owl Puzzle/Crown Dungeon (B1F): Owl Puzzle"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Two-Statue Puzzle/Crown Dungeon (B1F): Two-Statue Puzzle"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Dark Room/Crown Dungeon (B1F): Dark Room"},
	 { "@Dungeons/Crown Dungeon (D5)/(B1F): Six-Statue Puzzle/Crown Dungeon (B1F): Six-Statue Puzzle"},
	 { "@Dungeons/Crown Dungeon (D5)/Smog/Crown Dungeon (1F): Boss"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Vire Chest/Mermaid's Cave (Present): Vire Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Spinner Chest/Mermaid's Cave (Present): Spinner Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Rope Chest/Mermaid's Cave (Present): Rope Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/RNG Chest/Mermaid's Cave (Present): RNG Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Diamond Chest/Mermaid's Cave (Present): Diamond Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Beamos Chest/Mermaid's Cave (Present): Beamos Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Cube Chest/Mermaid's Cave (Present): Cube Chest"},
	 { "@Dungeons/Mermaid's Cave [Present] (D6)/Channel Chest/Mermaid's Cave (Present): Channel Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Stalfos Chest/Mermaid's Cave (Past) (1F): Stalfos Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Color Room/Mermaid's Cave (Past) (1F): Color Room"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Pool Chest/Mermaid's Cave (Past) (1F): Pool Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Wizzrobe/Mermaid's Cave (Past) (1F): Wizzrobe"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Diamond Chest/Mermaid's Cave (Past) (B1F): Diamond Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Spear Chest/Mermaid's Cave (Past) (B1F): Spear Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Rope Chest/Mermaid's Cave (Past) (B1F): Rope Chest"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/Octogon/Mermaid's Cave (Past) (1F): Boss"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Island Chest/Jabu-Jabu's Belly (1F): Island Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Stairway Chest/Jabu-Jabu's Belly (1F): Stairway Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Miniboss Chest/Jabu-Jabu's Belly (1F): Miniboss Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Cane and Diamond Puzzle/Jabu-Jabu's Belly (1F): Cane and Diamond Puzzle"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Boxed Chest/Jabu-Jabu's Belly (1F): Boxed Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Flower Room/Jabu-Jabu's Belly (1F): Flower Room"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Diamond Puzzle/Jabu-Jabu's Belly (1F): Diamond Puzzle"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Crab Chest/Jabu-Jabu's Belly (1F): Crab Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Left Wing/Jabu-Jabu's Belly (2F): Left Wing"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Right Wing/Jabu-Jabu's Belly (2F): Right Wing"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Spike Chest/Jabu-Jabu's Belly (2F): Spike Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Hallway Chest/Jabu-Jabu's Belly (3F): Hallway Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Post-Hallway Chest/Jabu-Jabu's Belly (3F): Post-Hallway Chest"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Terrace/Jabu-Jabu's Belly (3F): Terrace"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/Plasmarine/Jabu-Jabu's Belly (2F): Boss"},
	 { "@Dungeons/Ancient Tomb (D8)/(1F): Single Chest/Ancient Tomb (1F): Single Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): Maze Chest/Ancient Tomb (B2F): Maze Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): NW Slate Chest/Ancient Tomb (B2F): NW Slate Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): NE Slate Chest/Ancient Tomb (B2F): NE Slate Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): Ghini Chest/Ancient Tomb (B2F): Ghini Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): SE Slate Chest/Ancient Tomb (B2F): SE Slate Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): SW Slate Chest/Ancient Tomb (B2F): SW Slate Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): NW Chest/Ancient Tomb (B1F): NW Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): Sarcophagus Chest/Ancient Tomb (B1F): Sarcophagus Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): Blade Trap/Ancient Tomb (B1F): Blade Trap"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): Blue Peg Chest/Ancient Tomb (B1F): Blue Peg Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): Floor Puzzle/Ancient Tomb (B1F): Floor Puzzle"},
	 { "@Dungeons/Ancient Tomb (D8)/(B2F): Tile Room/Ancient Tomb (B2F): Tile Room"},
	 { "@Dungeons/Ancient Tomb (D8)/(B1F): Stalfos/Ancient Tomb (B1F): Stalfos"},
	 { "@Dungeons/Ancient Tomb (D8)/(B3F): Single Chest/Ancient Tomb (B3F): Single Chest"},
	 { "@Dungeons/Ancient Tomb (D8)/Ramrock/Ancient Tomb (B3F): Boss"},
	 { "@Dungeons/Hero's Cave/(1F): Pots Puzzle/Linked Hero's Cave (1F): Pots Puzzle"},
	 { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #1/Linked Hero's Cave (1F): Statue Puzzle #1"},
	 { "@Dungeons/Hero's Cave/(1F): Bridge Puzzle #1/Linked Hero's Cave (1F): Bridge Puzzle #1"},
	 { "@Dungeons/Hero's Cave/(1F): Shoot Eyes/Linked Hero's Cave (1F): Shoot Eyes"},
	 { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #2/Linked Hero's Cave (1F): Statue Puzzle #2"},
	 { "@Dungeons/Hero's Cave/(1F): Pots Puzzle #2/Linked Hero's Cave (1F): Pots Puzzle #2"},
	 { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #3/Linked Hero's Cave (1F): Statue Puzzle #3"},
	 { "@Dungeons/Hero's Cave/(1F): Bridge Puzzle #2/Linked Hero's Cave (1F): Bridge Puzzle #2"},
	 { "@Dungeons/Hero's Cave/(1F): Color Room/Linked Hero's Cave (1F): Color Room"},
	 { "@Dungeons/Hero's Cave/(1F): Water Puzzle/Linked Hero's Cave (1F): Water Puzzle"},
	 { "@Dungeons/Hero's Cave/(B1F): Water Puzzle/Linked Hero's Cave (B1F): Water Puzzle"},
	 { "@Dungeons/Hero's Cave/(B1F): Basement/Linked Hero's Cave (B1F): Basement"},
	 { "@Dungeons/Hero's Cave/(1F): Minecart Room/Linked Hero's Cave (1F): Minecart Room"},
	 { "@Dungeons/Hero's Cave/(1F): Completion Reward/Linked Hero's Cave (1F): Completion Reward"},
	 { "@Dungeons/Spirit's Grave (D1)/Eternal Spirit/Spirit's Grave: Essence"},
	 { "@Dungeons/Wing Dungeon (D2)/Ancient Wood/Wing Dungeon: Essence"},
	 { "@Dungeons/Moonlit Grotto (D3)/Echoing Howl/Moonlit Grotto: Essence"},
	 { "@Dungeons/Skull Dungeon (D4)/Burning Flame/Skull Dungeon: Essence"},
	 { "@Dungeons/Crown Dungeon (D5)/Sacred Soil/Crown Dungeon: Essence"},
	 { "@Dungeons/Mermaid's Cave [Past] (D6)/Lonely Peak/Mermaid's Cave: Essence"},
	 { "@Dungeons/Jabu-Jabu's Belly (D7)/Rolling Sea/Jabu-Jabu's Belly: Essence"},
	 { "@Dungeons/Ancient Tomb (D8)/Falling Star/Ancient Tomb: Essence"},
	 { "@Overworld/Lynna City/Lynna City: Seed Tree/Lynna City: Seed Tree"},
	 { "@Overworld_Past/Lynna Village/Ambi's Palace: Seed Tree/Ambi's Palace: Seed Tree"},
	 { "@Overworld_Past/Deku Forest/Deku Forest: Seed Tree/Deku Forest: Seed Tree"},
	 { "@Overworld/Crescent Island/Crescent Island: Seed Tree/Crescent Island: Seed Tree"},
	 { "@Overworld/Symmetry City/Symmetry City: Seed Tree/Symmetry City: Seed Tree"},
	 { "@Overworld_Past/Rolling Ridge/Rolling Ridge West: Seed Tree/Rolling Ridge West: Seed Tree"},
	 { "@Overworld_Past/Rolling Ridge/Rolling Ridge East: Seed Tree/Rolling Ridge East: Seed Tree"},
	 { "@Overworld/Zora Seas/Zora Village: Seed Tree/Zora Village: Seed Tree"},
}

function BuildLocationMapping()
    local location_mapping = {}
    local currentIndex = BASE
    for _, location in ipairs(LOCATION_LISTING) do
        if type(location) == "number" then
            currentIndex = currentIndex + location
        else
            location_mapping[currentIndex] = location
            currentIndex = currentIndex + 1
        end
    end

    return location_mapping
end

LOCATION_MAPPING = BuildLocationMapping()
