-- Dungeon entrance connection TODO: support entrance shuffle
d0_entrance:connect_two_ways(enter_d0)
d1_entrance:connect_two_ways(enter_d1)
d2_present_entrance:connect_two_ways(enter_d2)
d2_past_entrance:connect_two_ways(enter_d2)
d3_entrance:connect_two_ways(enter_d3)
d4_entrance:connect_two_ways(enter_d4)
d5_entrance:connect_two_ways(enter_d5)
d6_past_entrance:connect_two_ways(enter_d6_past)
d6_present_entrance:connect_two_ways(enter_d6_present)
d7_entrance:connect_two_ways(enter_d7)
d8_entrance:connect_two_ways(enter_d8)
